### ISSUE TITLE
Feature Request: Audio Upload

### ISSUE THREAD

**Issue by mrjarbenne** [jithin-space/h5p-ImageSequencing#4]
Similar to the audio upload feature available in the dialogue card h5p type (https://github.com/h5p/h5p-dialogcards). It would be amazing if the option were available to add an audio feature to each card. This would be similar to the text option, but would allow users who can't read the word, to hear the word read to them. 

This is the entry panel for the Dialogue Card type:

![2017-10-16_19-01-18](https://user-images.githubusercontent.com/480667/31639039-b9ab22ba-b2a4-11e7-827b-80a12c909292.png)

We are working of creating activities for young students to take words and pictures and sequence them into a sentence. Being able to play audio on each sequence card would make this activity richer. 

Thanks for considering this request.

**Comment by jithin-space** [comment]
Audio functionality is Implemented and is submitted for the review. Hope it will get added soon :)
