### ISSUE TITLE
Image Sequencing library doesn't give grade for Moodle

### ISSUE THREAD

**Issue by Jarvil** [jithin-space/h5p-ImageSequencing#5]
Hello,

It seems that Image Secuquencing -library gives users points f.ex 3/3 points but doesn't deliver these to moodle grade book / grader report like f.ex course presentation does.

**Comment by BV52** [comment]
Hi Jithin,

I was able to reproduce the issue using Moodle 3.3.2+ (Build: 20170928) on a macOS Sierra (V10.12.3).

-BV52

**Comment by jithin-space** [comment]
Hi ,
Image Sequencing Content type currently has no xApi Support for delivering data to the platform. It will be definitely included in the next release.

**Comment by niallmurphy-ie** [comment]
Hi, @jithin-space 

Do you have any idea of when xApi might be added?

Thanks.

**Comment by jithin-space** [comment]
Next version of Image Sequencing is Finished. It is submitted for the review. Hope it will get added soon. 
Latest code is available in the v2_development branch.

**Comment by niallmurphy-ie** [comment]
Thanks!

**Comment by jithin-space** [comment]
Image Sequencing version 2 was released 2/3 months ago. Please check the latest version at H5P Hub :)

**Comment by tommodl** [comment]
Hello, and thank you for writing back. The H5P module in our Moodle instance doesn’t have that update yet. I’ll work with our web dev team to implement. Thanks again for your quick response.

Tom Modl
Digital Projects Manager
Paradigm Education Solutions/JIST Career Solutions
tom.modl@paradigmeducation.com
(W) 651-215-7675
(M) 651-357-4883
[Paradigm logo][Jist_full-color]
